spring:
  application:
    name: AI
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: lyk
    password: 12345


  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
      embedding:
        options:
          model: mxbai-embed-large

    vectorstore:
     chroma:
       client:
         host: http://localhost
         port: 8000
       initialize-schema: true







server:
  port: 8001
milvus:
  host: 192.168.3.17
  port: 19530
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.itheima.ai: debug

    
