spring:
  application:
    name: AI
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b


server:
  port: 8000
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.itheima.ai: debug

    
